config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :recipes
  resources :categories
 
  get '/favourites' => 'favourites#index'
  delete '/favourites/:id' => 'favourites#destroy', as: :destroy_favourite
  post '/favourites/:id' => 'favourites#create', as: :add_to_favourites
  root 'recipes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :recipes
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
	belongs_to :user 
	belongs_to :recipe
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true

  def self.search(query)
    where('title like ?', "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :favourites
  has_many :providers
  has_many :recipes, through: :favourites
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]

  def self.from_omniauth(auth)
    provider = Provider.where(uid: auth.uid, name: auth.provider).first

    if provider
      user = provider.user
    else
      user = User.where(email: auth.info.email).first_or_initialize
    end

    unless user.persisted?
      user.password = Devise.friendly_token[0, 20]
      user.email = auth.info.email
    end

    user.save!

    Provider.find_or_create_by(uid: auth.uid, name: auth.provider, user: user)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def check_admin
    if current_user.admin != true
      redirect_to recipes_path, alert: 'Nie masz uprawnień, aby wykonać daną czynność!'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :add_allow_credentials_headers

  def add_allow_credentials_headers
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes.page(params[:page]).per(9)
  end

  def index
    @categories = Category.all
    render json: @categories
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @recipes = current_user.recipes.page(params[:page]).per(9)
  end

  def destroy
    current_user.favourites.where(recipe_id: params[:id]).destroy_all
    redirect_to favourites_path
  end

  def create
    if current_user.favourites.where(recipe_id: params[:id]).exists?
      redirect_to favourites_path, alert: 'Przepis jest już w ulubionych'
    elsif
      @recipe = Recipe.find(params[:id])
      current_user.recipes << @recipe
      redirect_to favourites_path, notice: 'Pomyślnie dodano'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :update, :edit, :create, :destroy]
  before_filter :check_admin, except: [:show, :index]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:search]
      @recipes = Recipe.search(params[:search]).order('created_at DESC').page(params[:page]).per(9)
    else
      @recipes = Recipe.order('created_at DESC').page(params[:page]).per(9)
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    url = recipe_params[:url]

    if url.include? 'kuchnialidla.pl'
      @recipe = LidlDownloader.new(url).przepis
    elsif url.include? 'kwestiasmaku.com'
      @recipe = KwestiaSmakuDownloader.new(url).przepis
    elsif url.include? 'codogara.pl'
      @recipe = CodogaraDownloader.new(url).przepis
    end

    @recipe.category_id = params[:recipe][:category_id]

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Przepis został poprawnie dodany.' }
        format.json { render :show, status: :created, location: recipes_path }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Przepis został pomyślnie zaktualizowany.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Przepis został poprawnie usunięty.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :description, :url, :category_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def login(name)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => name) if is_navigational_format?
    else
      session["devise.#{name}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook
    login("facebook")
  end

  def github
    login("github")
  end
  
  def google_oauth2
    login("google_oauth2")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= render partial: 'recipes/list', locals: { recipes: @recipes } %>

app/views/favourites/index.html.erb
<h1>Ulubione</h1>

<%= render partial: 'recipes/list', locals: { recipes: @recipes } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookBook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row hidden-print">
        <div class="col-md-3">
          <%= link_to 'Strona główna', recipes_path, :class => 'btn btn-default' %>
          <a class="btn btn-default navbar-btn" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">Menu
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.order("name").each do |category| %>
              <li><%= link_to "#{category.name} (#{category.recipes.count})", category %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-md-9">
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Zalogowany jako
            <strong><%= current_user.email %></strong>.
            <%= link_to 'Edytuj profil', edit_user_registration_path, :class => 'navbar-link' %>
              |
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              |
            <% if current_user.admin == true %>
                <%= link_to "Dodaj przepis", new_recipe_path %>
                |
            <% end %>
              <% if user_signed_in? %>
                <%=link_to "Ulubione przepisy (#{current_user.recipes.count})", favourites_path, :class =>'navbar-link' %>
              <% end %>
            <% else %>
              <%= link_to "Załóż konto", new_user_registration_path, :class => 'navbar-link'  %>
              |
            <%= link_to "Zaloguj się", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </div>
        </div>
        <div class="row hidden-print">
          <div class="col-md-4">
            <%= form_tag(recipes_path, :method => "get", id: "recipe-form") do %>
              <div class="form-group has-feedback">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Wyszukaj przepis" %>
                <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
              </div>
            <% end %>
          </div>
        </div>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <div class="row">
          <%= t("test.wiadomosc") %>
          <div class="col-md-12"><%= yield %></div>
        </div>
      </div>
    </body>
  </html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>Przepis został już dodany</h2>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-xs-4">
      Adres:
      <%= f.text_field :url, class: 'form-control', value: params[:url] %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-xs-4">
      Kategoria:
       <%= f.select :category_id, Category.order("name").collect { |p| [ p.name, p.id ] }, {include_blank: false}, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Utwórz przepis", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/recipes/_list.html.erb
<% recipes.each_slice(3) do |slice| %>
  <div class="row">
    <% slice.each do |recipe| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%=link_to image_tag(recipe.image), recipe %>
          <div class="caption">
            <h3><%= recipe.title %></h3>
            <p>
              <%= link_to 'Pokaż', recipe, class: "btn btn-default" %>
              <% if user_signed_in? && current_user.favourites.where(recipe_id: recipe.id).none? %>
                <%= link_to 'Dodaj do ulubionych', add_to_favourites_path(recipe.id), method: :post, class: "btn btn-default"%>
              <% end %>
              <% if  user_signed_in? && current_user.admin == true%>
                <% link_to 'Edytuj', edit_recipe_path(recipe), class: "btn btn-default" %>
                <%= link_to 'Usuń', recipe, method: :delete, data: { confirm: 'Jesteś pewien?' }, class: "btn btn-default" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edytuj przepis</h1>
<%= render 'form' %>
<%= link_to 'Pokaż', @recipe %> |
<%= link_to 'Wróć', recipes_path %>

app/views/recipes/index.html.erb
<h1>Księga Najlepszych Przepisów</h1>
<br>
<%= render partial: 'recipes/list', locals: { recipes: @recipes } %>
<%= paginate @recipes %>

app/views/recipes/new.html.erb
<h1>Nowy Przepis</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<p>
  <h1><%= @recipe.title %></h1>
</p>
<div class="row">
  <div class="col-md-4">
    <h2>Składniki</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-4 skladniki">
    <%= simple_format @recipe.ingredients %>
  </div>
  <div class="col-md-8">
    <%=image_tag @recipe.image %>
  </div>
</div>
<hr>
<h2>Przygotowanie</h2>
<br />
<div class="tresc-przepisu">
  <%= simple_format(@recipe.description) %>
</div>
<p>
  <strong>Autor:</strong>
  <%= link_to @recipe.url, @recipe.url, target:"_blank" %>
</p>
<a class="hidden-print btn btn-default" href="#" onclick="window.print();return false;">Drukuj przepis</a>
<%= link_to 'Wróć', recipes_path, :class => 'btn btn-default' %>